org.gradle.jvmargs=-Xmx30G
org.gradle.daemon=false
org.gradle.warning.mode=none
mixin.gradle.disableDiffplug=true

# Minecraft + Forge versions
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings
mapping_channel=official
mapping_version=1.20.1

# Mod metadata
mod_id=projectatmosphere
mod_name=Project Atmosphere
mod_group_id=net.Gabou.projectatmosphere
mod_license=All Rights Reserved
mod_version=0.3.0
mod_authors=Gabou
mod_description=Dynamic seasonal temperature and weather simulation with support for Serene Seasons and shaders.
mod_mixins=projectatmosphere.mixins.json
logo_file=src/main/resources/assets/projectatmosphere/icon.png
mod_logo_file=src/main/resources/assets/projectatmosphere/icon.png

api_version=1.3-1.20.1
api_version_range=[1.3-1.20.1,)

crackerslib_version=1.20.1-0.4.6
crackerslib_version_range=[1.20.1-0.4.6,)



# Dependencies
geckolib_version=4.7.1.2
midnightlib_forge_version=1.4.2
