pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven { url = 'https://maven.parchmentmc.org' }
    }
}
buildscript {
    repositories {
        maven {
            name = 'Sponge'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
            content {
                includeGroupByRegex('org\\.spongepowered.*')
            }
        }
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
            content {
                includeGroup('cpw.mods')
                includeGroupByRegex('net\\.minecraftforge.*')
            }
        }
        mavenCentral()
    }
}

rootProject.name = 'project-atmosphere'
