package net.Gabou.projectatmosphere.clouds.client.render.volumetric;

import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;

/**
 * Deterministic, allocation-bounded vertical diagnostic for the descriptor-owned
 * storm composition. It makes the field stages observable without treating
 * descriptor roles as independent media.
 *
 * <p>Lighting is deliberately represented as a supplied probe: primary field
 * evaluation is CPU-authoritative, while optical depth/direct/ambient/phase are
 * generated by the fragment path. The runtime capture owner supplies those
 * values from the same ray sample rather than duplicating lighting equations
 * on the CPU.
 */
final class StormMaterialContinuityDiagnostics {
    static final double MAX_INTERVAL_BLOCKS = 16.0D;

    private StormMaterialContinuityDiagnostics() {
    }

    static Trace trace(
            StormFieldSampler sampler,
            List<StormLobeDescriptor> lobes,
            double worldX,
            double worldZ,
            double minimumY,
            double maximumY,
            double interval,
            LightingProbe lightingProbe
    ) {
        if (interval <= 0.0D || interval > MAX_INTERVAL_BLOCKS) {
            throw new IllegalArgumentException("vertical material interval must be in (0, 16] blocks");
        }
        List<Sample> samples = new ArrayList<>();
        double[] fields = new double[2];
        for (double y = minimumY; y <= maximumY + 1.0E-6D; y += interval) {
            double coverage = sampler.coverageAt(lobes, worldX, y, worldZ);
            double strength = sampler.envelopeStrengthAt(lobes, worldX, y, worldZ);
            sampler.noiseFieldsAt(worldX, y, worldZ, fields);
            EnumSet<StormLobeDescriptor.Role> roles = activeRoles(lobes, worldX, y, worldZ);
            boolean embeddedConvectiveOverlap = roles.contains(StormLobeDescriptor.Role.BASE)
                    && roles.contains(StormLobeDescriptor.Role.CORE)
                    && roles.contains(StormLobeDescriptor.Role.TOWER);
            double coreFill = embeddedConvectiveOverlap
                    ? StormDensityModel.coreFillForCoverageAndStrength(coverage, strength)
                    : StormDensityModel.coreFillForEnvelopeStrength(strength);
            double body = StormDensityModel.stormBody(
                    coverage, strength, fields[0], embeddedConvectiveOverlap);
            double density = sampler.composition() == StormFieldSampler.Composition.AUDITED_PHASE_4R
                    ? sampler.densityFromFields(coverage, strength, fields[0], fields[1])
                    : StormDensityModel.finalDensity(
                            coverage, strength, fields[0], fields[1], embeddedConvectiveOverlap);
            double height01 = dominantHeight01(lobes, worldX, y, worldZ);
            Lighting lighting = lightingProbe == null
                    ? Lighting.unavailable()
                    : lightingProbe.sample(worldX, y, worldZ, density, height01);
            samples.add(new Sample(
                    y,
                    roles,
                    coverage,
                    strength,
                    fields[0],
                    fields[1],
                    body,
                    Math.max(body - density, 0.0D),
                    density,
                    coreFill,
                    height01,
                    lighting.extinction(),
                    lighting.opticalDepth(),
                    lighting.direct(),
                    lighting.ambient(),
                    lighting.phaseShadow(),
                    lighting.finalContribution(),
                    lighting.branchFlags()
            ));
        }
        return new Trace(worldX, worldZ, interval, List.copyOf(samples));
    }

    private static EnumSet<StormLobeDescriptor.Role> activeRoles(
            List<StormLobeDescriptor> lobes,
            double x,
            double y,
            double z
    ) {
        EnumSet<StormLobeDescriptor.Role> roles = EnumSet.noneOf(StormLobeDescriptor.Role.class);
        for (StormLobeDescriptor lobe : lobes) {
            if (StormLobeEvaluator.signedDistanceAt(lobe, x, y, z)
                    <= StormLobeEvaluator.edgeWidthBlocks(lobe)) {
                roles.add(lobe.role());
            }
        }
        return roles;
    }

    private static double dominantHeight01(
            List<StormLobeDescriptor> lobes,
            double x,
            double y,
            double z
    ) {
        double accumulated = 0.0D;
        double weight = 0.0D;
        for (StormLobeDescriptor lobe : lobes) {
            double distance = StormLobeEvaluator.signedDistanceAt(lobe, x, y, z);
            double localWeight = 1.0D - StormDensityModel.smoothstep(
                    0.0D,
                    StormLobeEvaluator.edgeWidthBlocks(lobe),
                    distance
            );
            if (localWeight <= 0.0D) {
                continue;
            }
            double base = StormLobeEvaluator.roleBaseY(lobe);
            double top = StormLobeEvaluator.roleTopY(lobe);
            accumulated += localWeight * StormDensityModel.clamp01((y - base) / Math.max(top - base, 1.0D));
            weight += localWeight;
        }
        return weight <= 0.0D ? 0.0D : accumulated / weight;
    }

    @FunctionalInterface
    interface LightingProbe {
        Lighting sample(double x, double y, double z, double finalDensity, double height01);
    }

    record Lighting(
            double extinction,
            double opticalDepth,
            double direct,
            double ambient,
            double phaseShadow,
            double finalContribution,
            String branchFlags
    ) {
        static Lighting unavailable() {
            return new Lighting(
                    Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN,
                    "cpu-field-only; shader-light-capture-required"
            );
        }
    }

    record Sample(
            double y,
            EnumSet<StormLobeDescriptor.Role> activeRoles,
            double coverage,
            double envelopeStrength,
            double baseNoise,
            double detailErosionInput,
            double bodyBeforeErosion,
            double detailErosion,
            double finalDensity,
            double coreFill,
            double height01,
            double extinction,
            double opticalDepth,
            double directLighting,
            double ambientLighting,
            double phaseShadowContribution,
            double finalRenderedContribution,
            String branchFlags
    ) {
    }

    record Trace(double worldX, double worldZ, double interval, List<Sample> samples) {
        Sample largestDensityStep() {
            Sample result = null;
            double largest = Double.NEGATIVE_INFINITY;
            for (int index = 1; index < samples.size(); index++) {
                double delta = Math.abs(samples.get(index).finalDensity()
                        - samples.get(index - 1).finalDensity());
                if (delta > largest) {
                    largest = delta;
                    result = samples.get(index);
                }
            }
            return result;
        }
    }
}
